### ISSUE TITLE
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by htelsiz** [toehio/s3album#4]
Getting an error using publish.js. The response from Amazon says "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256".

A stackoverflow post suggests using the following config:

```
AWS.config.update({
    signatureVersion: 'v4'
});
```

I just want to be able to make my own albums. Also, if you're still working on this, I'd love to start contributing.

**Comment by toehio** [comment]
Hi @htelsiz,

Thank you catching this bug. Have you tried adding `signatureVersion: 'v4'`? You could try adding it here
https://github.com/toehio/s3album/blob/master/publish.js#L649
and here
https://github.com/toehio/s3album/blob/master/publish.js#L657

If that works, could you please make a PR?

**Comment by htelsiz** [comment]
Hey @toehio, sure. I just tried it, but I'm getting another error (using the endpoint `s3.us-east-1.amazonaws.com`:

(from the console)

`Failed to load https://s3.us-east-1.amazonaws.com/ctr-auction-photos?delimiter=%2F&prefix=public-albums%2Falbums%2F: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://s3.us-east-2.amazonaws.com' is therefore not allowed access.`

However, I think this may be an issue with my bucket's CORS configuration. Can you let me know if you've experienced this error, and if you did, what did you do to solve it? After I work this out, I'll definitely open a PR. Thanks!

Edit: using the following endpoint setting:
`s3.us-east-2.amazonaws.com`

I get this error:

`AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-east-2'`

**Comment by htelsiz** [comment]
Hey, I figured that issue out, but I'm having another one. Hopefully I'm not bothering you. 

I can successfully select pictures from my bucket and create an album, but when I go to the published link, I see this error:

`<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>albums/view.html</Key>
<RequestId>ED7FA701F593510F</RequestId>
<HostId>
gE+QJtswVDyXx55XwB55B+RJNjeUe0Gws3jNcw59HNn7foW7P2fQ8smw5Am4few9ZYw89Lc0XHE=
</HostId>
</Error>`

By the way, I opened a PR with the changes.

**Comment by toehio** [comment]
@htelsiz I think you may have the wrong permissions for public access on the bucket. Please have a look at the example config in the README.

**Comment by htelsiz** [comment]
@toehio I got it all under control!

I'd like to start doing a lot of work on this repo; do you think you'd be willing to give me write access to the master branch after a few quality commits?

**Comment by toehio** [comment]
That's great! Can we start off doing pull requests?
