### ISSUE TITLE
Error specifying region

### ISSUE THREAD

**Issue by gwlund** [toehio/s3album#7]
Thank you for this great tool.  When I enter my preferences into publish.html and submit it says I'm using the wrong region.  My bucket is in 'us-west-2' region.  How would I specify the region?  I see some default variables in publish.html.  Is that the right place?  

Regards,
Gil.

**Comment by toehio** [comment]
Hi Gil,

The region is part of the endpoint address:
https://docs.aws.amazon.com/general/latest/gr/rande.html

By changing the endpoint, you should be able to specify the region.

Please let us all know if that worked for you to change the region.

**Comment by gwlund** [comment]
Thanks for the tip.  I changed the end-point to include the region and noticed that publish.html autodetected it but when I submit I get a "NetworkingError: Network Failure" error.

**Comment by GeordiePigeonOwner** [comment]
I am also getting this error.

do you have a single region only bucket. I have. could this be it?

How do we fix this?

**Comment by dcgomesbr** [comment]
I forked the project with the fix here:
https://github.com/dcgomesbr/s3album

**Comment by toehio** [comment]
@dcgomesbr thank you! Can you please make a pull request?

**Comment by toehio** [comment]
Fixed by #8
